#!/usr/bin/env bash
# Generate compiled-in web assets from web/ directory.
# Output: src/web-assets.c
# Usage: ./scripts/gen-web-assets.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"
WEB_DIR="$ROOT_DIR/web"
OUT_C="$ROOT_DIR/src/web-assets.c"

if [ ! -d "$WEB_DIR" ]; then
    echo "error: web/ directory not found" >&2
    exit 1
fi

# Collect all files
FILES=()
while IFS= read -r -d '' f; do
    FILES+=("$f")
done < <(find "$WEB_DIR" -type f \( -name '*.html' -o -name '*.css' -o -name '*.js' -o -name '*.svg' \) -print0 | sort -z)

if [ ${#FILES[@]} -eq 0 ]; then
    echo "error: no web assets found in web/" >&2
    exit 1
fi

# Start generating C file
cat > "$OUT_C" << 'HEADER'
/* SPDX-License-Identifier: MIT */
/* Auto-generated by scripts/gen-web-assets.sh -- do not edit. */

#ifdef KBOX_HAS_WEB

#include <string.h>

HEADER

# Generate arrays for each file
ENTRIES=()
for filepath in "${FILES[@]}"; do
    relpath="${filepath#$WEB_DIR/}"
    # Generate C variable name: replace / . - with _
    varname="asset_$(echo "$relpath" | sed 's/[\/\.\-]/_/g')"

    # Generate array declaration manually (xxd -i from stdin varies by platform).
    # Strip any declaration lines xxd might emit (some versions wrap stdin).
    echo "/* $relpath */" >> "$OUT_C"
    echo "static const unsigned char ${varname}[] = {" >> "$OUT_C"
    xxd -i < "$filepath" | sed -e '/^unsigned/d' -e '/^};/d' >> "$OUT_C"
    echo "};" >> "$OUT_C"
    filesize=$(wc -c < "$filepath" | tr -d ' ')
    echo "static const unsigned int ${varname}_len = ${filesize};" >> "$OUT_C"
    echo "" >> "$OUT_C"

    # URL path: / and /index.html for index.html, otherwise /relpath
    if [ "$relpath" = "index.html" ]; then
        ENTRIES+=("${varname}|/")
        ENTRIES+=("${varname}|/index.html")
    else
        ENTRIES+=("${varname}|/$relpath")
    fi
done

# Generate lookup function
cat >> "$OUT_C" << 'LOOKUP_START'

/* Asset lookup table */
struct kbox_web_asset_entry {
    const char *path;
    const unsigned char *data;
    unsigned int len;
};

static const struct kbox_web_asset_entry kbox_web_assets[] = {
LOOKUP_START

for entry in "${ENTRIES[@]}"; do
    IFS='|' read -r varname urlpath <<< "$entry"
    echo "    {\"${urlpath}\", ${varname}, ${varname}_len}," >> "$OUT_C"
done

cat >> "$OUT_C" << 'LOOKUP_END'
};

static const int kbox_web_asset_count =
    (int)(sizeof(kbox_web_assets) / sizeof(kbox_web_assets[0]));

int kbox_web_asset_find(const char *path,
                        const unsigned char **data,
                        unsigned int *len)
{
    for (int i = 0; i < kbox_web_asset_count; i++) {
        if (strcmp(kbox_web_assets[i].path, path) == 0) {
            *data = kbox_web_assets[i].data;
            *len = kbox_web_assets[i].len;
            return 0;
        }
    }
    return -1;
}

#endif /* KBOX_HAS_WEB */
LOOKUP_END

echo "Generated $OUT_C with ${#FILES[@]} assets" >&2
